name: LinuxDo自动签到

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时执行一次
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.19'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r linuxdo_requirements.txt
          pip install requests
          playwright install --with-deps firefox

      - name: 执行脚本
        env:
          USERNAME: ${{ secrets.LINUXDO_USERNAME }}
          PASSWORD: ${{ secrets.LINUXDO_PASSWORD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python linuxdo_check_in.py


      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 10
          keep_minimum_runs: 6